name: Run Data Preprocessing

on:
  workflow_dispatch:
  push:
    paths:
      - /media/gede/2nd SSD/LaskarAI/Submission/MSML/preprocessing/diabet_preprocessing.csv
      - /media/gede/2nd SSD/LaskarAI/Submission/MSML/preprocessing/automate_Gede Pradnyananda.py

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clean MLflow logs
      run: rm -rf mlruns

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn mlflow==2.19.0 imbalanced-learn

    - name: Run Preprocessing
      run: python "preprocessing/automate_Gede Pradnyananda.py"
